# The OS X Build Environment
# https://docs.travis-ci.com/user/reference/osx/#xcode-version

branches:
  only:
  - master
  - development

language: objective-c
xcode_project: GRDB.xcodeproj

# Caches
cache:
  - bundler
  - cocoapods

# Custom CocoaPods installation so that Podfile.lock is honored
install:
  - bundle install
  - bundle exec pod repo update

# Disable the default Travis-CI submodule logic
# The various make commands ensure that the appropriate submodules are retrieved
git:
  submodules: false

jobs:
  include:

    ###########################################
    ## Test GRDB Xcode 12.2
    
    - name: "Test GRDB Xcode 12.2 - GRDBOSX - Swift 5.3"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_framework_GRDBOSX_maxSwift
    
    - name: "Test GRDB Xcode 12.2 - GRDBOSX - Swift 5.2"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_framework_GRDBOSX_minSwift
    
    - name: "Test GRDB Xcode 12.2 - GRDBWatchOS"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_framework_GRDBWatchOS
    
    - name: "Test GRDB Xcode 12.2 - GRDBiOS iOS maxTarget"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_framework_GRDBiOS_maxTarget_maxSwift
    
    - name: "Test GRDB Xcode 12.2 - GRDBiOS iOS minTarget"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_framework_GRDBiOS_minTarget
    
    - name: "Test GRDB Xcode 12.2 - GRDBtvOS maxTarget"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_framework_GRDBtvOS_maxTarget_maxSwift
    
    - name: "Test GRDB Xcode 12 - GRDBtvOS minTarget"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_framework_GRDBtvOS_minTarget
    
    - name: "Test GRDB Xcode 12.2 - SPM"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_SPM
    
    ###########################################
    ## Test GRDBCustom Xcode 12.2
    
    - name: "Test GRDBCustom Xcode 12.2 - GRDBOSX"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_framework_GRDBCustomSQLiteOSX
    
    - name: "Test GRDBCustom Xcode 12.2 - GRDBiOS maxTarget"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_framework_GRDBCustomSQLiteiOS_maxTarget_maxSwift
    
    - name: "Test GRDBCustom Xcode 12.2 - GRDBiOS minTarget"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_framework_GRDBCustomSQLiteiOS_minTarget
    
    ###########################################
    ## Test SQLCipher Xcode 12.2
    
    - name: "Test SQLCipher Xcode 12.2 - SQLCipher 3"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_framework_SQLCipher3
    
    - name: "Test SQLCipher Xcode 12.2 - SQLCipher 4"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_framework_SQLCipher4
    
    ###########################################
    ## Test Installation Xcode 12.2
    
    # Manual Install
    - name: "Test Installation Xcode 12.2 - Manual Install"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_install_manual
    
    # Travis is much too slow, and always fail this job
    # # CocoaPods Lint
    # - name: "Test Installation Xcode 12.2 - CocoaPods Lint"
    #   gemfile: .ci/gemfiles/Gemfile.travis
    #   osx_image: xcode12.2
    #   script: make test_CocoaPodsLint_GRDB
    
    # CocoaPods Install GRDB
    - name: "Test Installation Xcode 12.2 - CocoaPods Framework"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_install_GRDB_CocoaPods_framework
    
    # CocoaPods Install GRDB
    - name: "Test Installation Xcode 12.2 - CocoaPods Static"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_install_GRDB_CocoaPods_static
    
    # SPM Install
    - name: "Test Installation Xcode 12.2 - SPM Package"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_install_SPM_Package
    
    # SPM Install
    - name: "Test Installation Xcode 12.2 - SPM Package in Xcode Project"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_install_SPM_Project
    
    # Custom SQLite Install
    - name: "Test Installation Xcode 12.2 - Custom SQLite"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode12.2
      script: make test_install_customSQLite
    
    ###########################################
    ## Test GRDB Xcode 11.4
    
    - name: "Test GRDB Xcode 11.4 - GRDBiOS iOS maxTarget"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode11.4
      script: make test_framework_GRDBiOS_maxTarget_maxSwift
    
    - name: "Test GRDB Xcode 11.4 - GRDBiOS iOS minTarget"
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode11.4
      script: make test_framework_GRDBiOS_minTarget
