name: macOS

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # “At 11:00 on Saturday.”
    - cron: '0 11 * * SAT'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: Build
      run: xcodebuild -scheme Draggy build

    - name: Run tests
      run: xcodebuild test -scheme Draggy
      
    - name: Archive build artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build artifacts
        path: /Users/runner/Library/Developer/Xcode/DerivedData/
